from google.genai.errors import APIError, ServerError
from google import genai
import asyncio

from dotenv import load_dotenv
import os

load_dotenv()

if not os.getenv("GEMINI_API_KEY") and not os.getenv("GOOGLE_API_KEY"):
    raise RuntimeError(
        "Missing Gemini API key: set GEMINI_API_KEY (or GOOGLE_API_KEY) "
        "in your environment before starting the server."
    )

class GeminiInvocationError(Exception):
    """Raised when the Gemini call fails or returns something unusable.

    Callers should catch this specific exception (not bare Exception) and
    turn it into an appropriate HTTP response.
    """

client = genai.Client()

async def invoke(prompt: str | list) -> str:
    """
    Asynchronously generates content using the Gemini model.

    Args:
        prompt (str | list): The input text or list of contents to send to the model.

    Returns:
        str: The text response generated by the model.

    Raises:
        GeminiInvocationError: If the model returns an empty string, or if
            server-side, client-side, or unexpected errors occur during execution.
    """
    for attempt in range(5):
        try:
            response = await client.aio.models.generate_content(
                model="gemini-2.5-flash",  # Ensure this matches your target model
                contents=prompt,
            )

            result_text = response.text

            if not result_text:
                raise GeminiInvocationError("The Model Returned An Empty String")

            return result_text

        except APIError as error:
            # Check if it's the last attempt; if so, let it fail/raise out
            if attempt == 4:
                raise GeminiInvocationError("Encountered an API error after 5 attempts") from error

            # Use async sleep so you don't block the event loop
            await asyncio.sleep(60)

        except ServerError as error:
            raise GeminiInvocationError("Encountered a server-side exception from Gemini") from error

        except Exception as exception:
            # Catch-all for unexpected errors you don't want to silently retry
            raise GeminiInvocationError("Encountered an unexpected exception") from exception

if __name__ == "__main__":
    ...